baseURL = "https://alasutoru.github.io/me/"
languageCode = "en-us"
title = "alasutoru"
theme = "notrack"
pagination.pagerSize = 5  # Posts per page, e.g. in the blog

[params]
author = "alasutoru"
siteHeading = "alasutoru" # defaults to author
favicon = "hugo_grotius.png" # The small icon shown in browser tabs
showTaxonomyLinks = true  # Show e.g. a "Category" button at top of blog page

# You can choose to display a summary of your blog on the home page. Below are
# the settings relevant for that.
showBlogLatest = true  # Whether to show it or not
mainSections = ["blog"]  # Section name of your blog (folder name)
blogLatestHeading = "My writing"  # Heading above blog summary
nBlogLatest = 4  # Number of blog post in summary

[params.social]
github = "https://github.com/alasutoru"
email = "example@example.com"
mastodon = "example"
rss = "yes"

[taxonomies]
year = "year"
month = "month"
tags = "tags"
categories = "categories"

[permalinks]
  blog = "/blog/:year/:month/:slug"
